name: Update RaiPlaySound Feeds

on:
  schedule:
    - cron: "0 */1 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-feeds-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 lxml feedendum chardet python-dateutil certifi

      - name: Generate Feeds
        run: python scripts/generate_feeds.py
      - name: Debug - Verifica file generati
        run: |
          echo "Contenuto della directory:"
          ls -l
      - name: Verifica dimensione file XML
        run: |
          for file in feed_*.xml; do
            size=$(wc -c < "$file")
            if [ "$size" -lt 50 ]; then
              echo "Il file $file Ã¨ troppo piccolo, potrebbe essere vuoto!"
            fi
          done
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          commit_message: Aggiornamento automatico dei feeds
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          keep_files: false
          disable_nojekyll: true
